spring:
  datasource:
    url: jdbc:h2:mem:posts;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  sql:
    init:
      mode: always

app:
  images:
    upload-dir: uploads/images
    base-url: /images/

